# 语言配置
language: node_js
node_js:
  - 11

# 构建项目
script: npm run build

# push到github的web-deploy分支上
after_script:
  - git fetch
  - git checkout web-deploy
  - rm -rf ./css
  - rm -rf ./js
  - rm -rf ./index.html
  - cp -r ./dist/* .
  - git add .
  - git commit -m "deploy by travis ci"
  - git push "https://${TOKEN}@github.com/MyFaith/toplist.git" web-deploy:web-deploy

# 只监测master分支的修改
branches:
  only:
    - master