name: Auto deploy to Netlify

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v1
    - name: Install dependences
      run: |
        pwd
        ls
        npm install
    - name: Build
      run: npm run build
    - name: Copy files to deploy
      run: |
        git checkout web-deploy
        rm -rf ./css
        rm -rf ./js
        rm -rf ./index.html
        cp -r ./dist/* .
    - name: Deploy site
      run: |
        git config --global user.name "MyFaith'
        git config --global user.email "myfaith0725@gmail.com"
        git add .
        git commit -m "deploy by github actions"
        git push "https://${{ secrets.TOKEN }}@github.com/MyFaith/toplist.git" web-deploy:web-deploy
